config/routes.rb
Cis4375::Application.routes.draw do
  devise_for :users
  get 'pages/home'
  get 'pages/about'
  get 'pages/help'
  get 'pages/faq'
  get 'pages/tutorial'

  get 'customers/new_lead'
  post 'customers/create_lead'

  get 'customers/search'
  get 'jobs/search'
  get 'sales_agents/search'
  get 'job_sources/search'

  get 'jobs/jobs'
  get 'jobs/bids'
  get 'jobs/leads'
  get 'jobs/kitchens'
  get 'jobs/bathrooms'
  get 'jobs/all'

  get 'customers/active'
  get 'customers/inactive'

  resources :sales_agent_statuses

  resources :sales_agents

  resources :job_statuses

  resources :job_status_histories

  resources :job_types

  resources :job_sources

  resources :customer_statuses

  resources :jobs

  resources :customers

   root 'pages#home'

end

app/controllers/job_types_controller.rb
class JobTypesController < ApplicationController
  before_action :set_job_type, only: [:show, :edit, :update, :destroy]

  # GET /job_types
  # GET /job_types.json
  def index
    @job_types = JobType.all
  end

  # GET /job_types/1
  # GET /job_types/1.json
  def show
  end

  # GET /job_types/new
  def new
    @job_type = JobType.new
  end

  # GET /job_types/1/edit
  def edit
  end

  # POST /job_types
  # POST /job_types.json
  def create
    @job_type = JobType.new(job_type_params)

    respond_to do |format|
      if @job_type.save
        format.html { redirect_to @job_type, notice: 'Job type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @job_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_types/1
  # PATCH/PUT /job_types/1.json
  def update
    respond_to do |format|
      if @job_type.update(job_type_params)
        format.html { redirect_to @job_type, notice: 'Job type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_types/1
  # DELETE /job_types/1.json
  def destroy
    @job_type.destroy
    respond_to do |format|
      format.html { redirect_to job_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_type
      @job_type = JobType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_type_params
      params.require(:job_type).permit(:job_type_name)
    end
end

app/helpers/job_types_helper.rb
module JobTypesHelper
end

app/views/job_types/_form.html.erb
<%= form_for(@job_type) do |f| %>
  <% if @job_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_type.errors.count, "error") %> prohibited this job_type from being saved:</h2>

      <ul>
      <% @job_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_type_name %><br>
    <%= f.text_field :job_type_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_types/edit.html.erb
<h1>Editing job_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_type %> |
<%= link_to 'Back', job_types_path %>

app/views/job_types/index.html.erb
<h1>Listing job_types</h1>

<table>
  <thead>
    <tr>
      <th>Job type name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @job_types.each do |job_type| %>
      <tr>
        <td><%= job_type.job_type_name %></td>
        <td><%= link_to 'Show', job_type %></td>
        <td><%= link_to 'Edit', edit_job_type_path(job_type) %></td>
        <td><%= link_to 'Destroy', job_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job type', new_job_type_path %>

app/views/job_types/new.html.erb
<h1>New job_type</h1>

<%= render 'form' %>

<%= link_to 'Back', job_types_path %>

app/views/job_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job type name:</strong>
  <%= @job_type.job_type_name %>
</p>

<%= link_to 'Edit', edit_job_type_path(@job_type) %> |
<%= link_to 'Back', job_types_path %>