config/routes.rb
Cis4375::Application.routes.draw do
  devise_for :users
  get 'pages/home'
  get 'pages/about'
  get 'pages/help'
  get 'pages/faq'
  get 'pages/tutorial'

  get 'customers/new_lead'
  post 'customers/create_lead'

  get 'customers/search'
  get 'jobs/search'
  get 'sales_agents/search'
  get 'job_sources/search'

  get 'jobs/jobs'
  get 'jobs/bids'
  get 'jobs/leads'
  get 'jobs/kitchens'
  get 'jobs/bathrooms'
  get 'jobs/all'

  get 'customers/active'
  get 'customers/inactive'

  resources :sales_agent_statuses

  resources :sales_agents

  resources :job_statuses

  resources :job_status_histories

  resources :job_types

  resources :job_sources

  resources :customer_statuses

  resources :jobs

  resources :customers

   root 'pages#home'

end

app/controllers/customer_statuses_controller.rb
class CustomerStatusesController < ApplicationController
  before_action :set_customer_status, only: [:show, :edit, :update, :destroy]

  # GET /customer_statuses
  # GET /customer_statuses.json
  def index
    @customer_statuses = CustomerStatus.all
  end

  # GET /customer_statuses/1
  # GET /customer_statuses/1.json
  def show
  end

  # GET /customer_statuses/new
  def new
    @customer_status = CustomerStatus.new
  end

  # GET /customer_statuses/1/edit
  def edit
  end

  # POST /customer_statuses
  # POST /customer_statuses.json
  def create
    @customer_status = CustomerStatus.new(customer_status_params)

    respond_to do |format|
      if @customer_status.save
        format.html { redirect_to @customer_status, notice: 'Customer status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer_status }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_statuses/1
  # PATCH/PUT /customer_statuses/1.json
  def update
    respond_to do |format|
      if @customer_status.update(customer_status_params)
        format.html { redirect_to @customer_status, notice: 'Customer status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_statuses/1
  # DELETE /customer_statuses/1.json
  def destroy
    @customer_status.destroy
    respond_to do |format|
      format.html { redirect_to customer_statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_status
      @customer_status = CustomerStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_status_params
      params.require(:customer_status).permit(:customer_status_name)
    end
end

app/helpers/customer_statuses_helper.rb
module CustomerStatusesHelper
end

app/views/customer_statuses/_form.html.erb
<%= form_for(@customer_status) do |f| %>
  <% if @customer_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_status.errors.count, "error") %> prohibited this customer_status from being saved:</h2>

      <ul>
      <% @customer_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_status_name %><br>
    <%= f.text_field :customer_status_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customer_statuses/edit.html.erb
<h1>Editing customer_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_status %> |
<%= link_to 'Back', customer_statuses_path %>

app/views/customer_statuses/index.html.erb
<h1>Listing customer_statuses</h1>

<table>
  <thead>
    <tr>
      <th>Customer status name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_statuses.each do |customer_status| %>
      <tr>
        <td><%= customer_status.customer_status_name %></td>
        <td><%= link_to 'Show', customer_status %></td>
        <td><%= link_to 'Edit', edit_customer_status_path(customer_status) %></td>
        <td><%= link_to 'Destroy', customer_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer status', new_customer_status_path %>

app/views/customer_statuses/new.html.erb
<h1>New customer_status</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_statuses_path %>

app/views/customer_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer status name:</strong>
  <%= @customer_status.customer_status_name %>
</p>

<%= link_to 'Edit', edit_customer_status_path(@customer_status) %> |
<%= link_to 'Back', customer_statuses_path %>