config/routes.rb
Cis4375::Application.routes.draw do
  devise_for :users
  get 'pages/home'
  get 'pages/about'
  get 'pages/help'
  get 'pages/faq'
  get 'pages/tutorial'

  get 'customers/new_lead'
  post 'customers/create_lead'

  get 'customers/search'
  get 'jobs/search'
  get 'sales_agents/search'
  get 'job_sources/search'

  get 'jobs/jobs'
  get 'jobs/bids'
  get 'jobs/leads'
  get 'jobs/kitchens'
  get 'jobs/bathrooms'
  get 'jobs/all'

  get 'customers/active'
  get 'customers/inactive'

  resources :sales_agent_statuses

  resources :sales_agents

  resources :job_statuses

  resources :job_status_histories

  resources :job_types

  resources :job_sources

  resources :customer_statuses

  resources :jobs

  resources :customers

   root 'pages#home'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :customer
  belongs_to :job_source
  belongs_to :job_type
  belongs_to :sales_agent, foreign_key: :sales_agent_id
  has_one :job_status
  has_many :job_status_histories
  has_many :job_statuses, through: :job_status_histories
  validates_presence_of :customer
  validates_numericality_of :job_price, allow_nil: true

  before_destroy {|record| JobStatusHistory.destroy_all "job_id = #{record.id}"}
  before_create {|record| if record.job_status_id == nil; record.job_status_id = 1 end} #default job_status if blank is Lead
  before_validation {|record| if record.job_status_id == 1; record.internal_job_id = nil elsif record.job_status_id == 2; record.internal_job_id = nil end}
  after_create {|record| record.job_status_histories.new(:job_status_id => record.job_status_id).save! } #create job status history
  after_update {|record| if record.job_status_id != record.job_status_histories.last.job_status_id; record.job_status_histories.new(:job_status_id => record.job_status_id).save! end}

  def self.search(search, criteria)
    if criteria
      find(:all, :conditions => ["#{criteria[0]} LIKE ?", '%'+search+'%'])
    else
      []
    end
  end

  def self.table_limit(limit)
    limit
  end

  def search_result
     "#{id} | #{customer.name_with_initial} | #{created_at}"
  end

end

app/models/job_type.rb
class JobType < ActiveRecord::Base
  has_many :jobs
  validates_uniqueness_of :job_type_name
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]


  # GET /jobs
  # GET /jobs.json
  def index
  end

  def all
    @jobs = Job.order('id DESC').limit(params[:limit]).all
    render layout: false
  end
  def kitchens
    @jobs_kitchen = Job.order('id DESC').limit(params[:limit]).where(:job_type_id => 2)
    render layout: false
  end
  def bids
    @jobs_bid = Job.order('id DESC').limit(params[:limit]).where(job_status_id:2)
    render layout: false
  end
  def leads
    @jobs_lead = Job.order('id DESC').limit(params[:limit]).where(job_status_id: 1)
    render layout: false
  end
  def bathrooms
    @jobs_bathroom = Job.order('id DESC').limit(params[:limit]).where(:job_type_id => 1)
    render layout: false
  end
  def jobs
    @jobs_job = Job.order('id DESC').limit(params[:limit]).where(job_status_id:3)
    render layout: false
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  def search
    @jobs = Job.search params[:search],params[:criteria]
  end

  # GET /jobs/new
  def new
    @job = Job.new
    @job_status_history = @job.job_status_histories.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:customer_id, :sales_agent_id, :job_source_id, :job_type_id, :internal_job_id, :customer_home_address, :customer_home_city, :customer_home_zip, :customer_home_state, :job_price, :job_notes, :job_status_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<% if @job.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@job.errors.count, "error") %>.
      </div>
      <ul>
        <% @job.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for @job, :html => { :class => 'form-horizontal' } do |f| %>


    <div class="control-group">
      <%= f.label :job_status, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select :job_status_id ,JobStatus.all, :id, :job_status_name %>
      </div>
    </div>
  <div class="control-group">
    <%= f.label :customer_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :customer_id, Customer.all.order(:customer_first_name), :id, :full_name, {:include_blank => 'Select a customer'}, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sales_agent_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :sales_agent_id, SalesAgent.order('sales_agent_first_name').all, :id, :name_with_initial,{include_blank:true}, :class => 'collection-select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :job_source_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :job_source_id, JobSource.all, :id, :job_source_name, {include_blank:true}, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :job_type_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :job_type_id, JobType.all, :id, :job_type_name, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
      <%= f.label :internal_job_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :internal_job_id, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <input type="checkbox" id="checkbox_address" checked>Use Customer's Address
    </div>
    <div class="control-group">
      <%= f.label :address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :customer_home_address, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :zip, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :customer_home_zip, :class => 'text_field zip-lookup-field-zipcode' %>
      </div>
    </div>
    </div>
    <div class="control-group">
      <%= f.label :city, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :customer_home_city, :class => 'text_field zip-lookup-field-city' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :state, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :customer_home_state, :class => 'text_field zip-lookup-field-state' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :price, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :job_price, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :notes, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :job_notes, :class => 'text_field' %>
      </div>
    </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                jobs_path, :class => 'btn' %>
  </div>
<% end %>

<script>

    $("#checkbox_address").on("change customer", function checkbox(){
        if (this.checked) {
            //set boxes readonly
            $("#job_customer_home_address").attr("readonly", "")
            $("#job_customer_home_zip").attr("readonly", "")
            $("#job_customer_home_city").attr("readonly", "")
            $("#job_customer_home_state").attr("readonly", "")

            //get customer address info
            var url = "<%= customers_path%>" + "/" + $("#job_customer_id").val()
            $.ajax({
                dataType: "json",
                url: url,
                success: function(data){

                    $("#job_customer_home_address").val(data["customer_home_address"])
                    $("#job_customer_home_zip").val(data["customer_home_zip"])
                    $("#job_customer_home_city").val(data["customer_home_city"])
                    $("#job_customer_home_state").val(data["customer_home_state"])
                }
            })

        } else {
            $("#job_customer_home_address").attr("readonly", false)
            $("#job_customer_home_zip").attr("readonly", false)
            $("#job_customer_home_city").attr("readonly", false)
            $("#job_customer_home_state").attr("readonly", false)
        }
    })

    $("#job_customer_id").on("change", function(){$("#checkbox_address").trigger("customer");});
    $("#checkbox_address").trigger("customer");


</script>

app/views/jobs/_search.html.erb
<%= form_tag jobs_search_path, :remote => true, :method => 'get', :class => 'form-inline' do %>
          <%= text_field_tag :search, params[:search], :id => 'search_field', :class => 'search-query' %>
          <%= collection_select :criteria, params[:to_s], Job.column_names, :to_s, :titleize, :class => 'text-field' %>
          <%= submit_tag "Find", :name => nil, :class => 'btn btn-info' %>
      <% end %>

<table id="results" class="table">
  <thead><th>Results:</th></thead>
  <% @jobs.each do |job| %>
      <tr></tr><td><%= link_to job.search_result , :action => 'show', :id => job.id  %></td></tr>
  <% end %>
</table>

<script>
    function search(){
        var url = $("#search > form").attr("action") + "?" + $("#search > form").serialize();
        var results_table = " #results"
        if ($("#search_field").val().length > 0) {
            $("#results").load(url + results_table)
        }
    }
    $("#search > form").submit(function(){search()})

    $("#search_field").on("keyup",function(){search()} )

    $("#criteria_").on("change", function(){search()})




</script>

app/views/jobs/all.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Id</th>
    <th>Internal #</th>
    <th>Customer</th>
    <th>Sales Agent</th>
    <th>Job Source</th>
    <th>Job Type</th>
    <th>Job Status</th>
    <th>Created_at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <%  @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.id, job_path(job) %></td>
        <td><%= job.internal_job_id %></td>
        <td><%= job.customer.name_with_initial %></td>
        <td><%= if job.sales_agent; job.sales_agent.name_with_initial end %></td>
        <td><%= if job.job_source_id; job.job_source.job_source_name end %></td>
        <td><%= if job.job_type; job.job_type.job_type_name end %></td>
        <td><%= if job.job_status_id; job.job_status_histories.last.job_status.job_status_name end %></td>
        <td><%=l job.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<p>Showing last 15 - <a href="#all" onclick=" tab1()">View All</a> </p>
<script>
  function tab1(){$("#tab1").load("/jobs/all")}
</script>

app/views/jobs/bathrooms.html.erb
<table class="table table-striped  tablesorter">
  <thead>
  <tr>
    <th>Id</th>
    <th>Internal #</th>
    <th>Customer</th>
    <th>Sales Agent</th>
    <th>Job Source</th>
    <th>Job Status</th>
    <th>Created_at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @jobs_bathroom.each do |job| %>
      <tr>
        <td><%= link_to job.id, job_path(job) %></td>
        <td><%= job.internal_job_id %></td>
        <td><%= job.customer.name_with_initial %></td>
        <td><%= if job.sales_agent; job.sales_agent.name_with_initial end %></td>
        <td><%= if job.job_source_id; job.job_source.job_source_name end %></td>
        <td><%= if job.job_status_id; job.job_status_histories.last.job_status.job_status_name end %></td>
        <td><%=l job.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<p>Showing last 15 - <a href="#all" onclick=" tab2()">View All</a> </p>
<script>
    function tab2(){$("#tab2").load("/jobs/bathrooms")}
</script>

app/views/jobs/bids.html.erb
<table class="table table-striped tablesorter">
  <thead>
  <tr>
    <th>Id</th>
    <th>Customer</th>
    <th>Sales Agent</th>
    <th>Job Source</th>
    <th>Job Type</th>
    <th>Created_at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @jobs_bid.each do |job| %>
      <tr>
        <td><%= link_to job.id, job_path(job) %></td>
        <td><%= job.customer.name_with_initial %></td>
        <td><%= if job.sales_agent; job.sales_agent.name_with_initial end %></td>
        <td><%= if job.job_source_id; job.job_source.job_source_name end %></td>
        <td><%= if job.job_type; job.job_type.job_type_name end %></td>
        <td><%=l job.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<p>Showing last 15 - <a href="#all" onclick=" tab5()">View All</a> </p>
<script>
    function tab5(){$("#tab5").load("/jobs/bids")}
</script>

app/views/jobs/edit.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/index.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

 <div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">All</a></li>
    <li><a href="#tab2" data-toggle="tab">Bathrooms</a></li>
    <li><a href="#tab3" data-toggle="tab">Kitchens</a></li>
    <li><a href="#tab4" data-toggle="tab">Leads</a></li>
    <li><a href="#tab5" data-toggle="tab">Bids</a></li>
    <li><a href="#tab6" data-toggle="tab">Jobs</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      Loading...
      <br>
    </div>
    <div class="tab-pane" id="tab2">
      Loading...
      <br>
    </div>
    <div class="tab-pane" id="tab3">
      Loading...
      <br>
    </div>
    <div class="tab-pane" id="tab4">
      Loading...
      <br>
    </div>
    <div class="tab-pane" id="tab5">
      Loading...
      <br>
    </div>
    <div class="tab-pane" id="tab6">
      Loading...
      <br>
    </div>
  </div>
</div>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-primary' %>

<script>
    $("#tab1").load("/jobs/all?limit=15", function(){

        $("#tab2").load("/jobs/bathrooms?limit=15")

        $("#tab3").load("/jobs/kitchens?limit=15")

        $("#tab4").load("/jobs/leads?limit=15")

        $("#tab5").load("/jobs/bids?limit=15")

        $("#tab6").load("/jobs/jobs?limit=15", function(){
        //to sort any table in this application
        $("table").tablesorter({debug: false})})

    })


</script>

app/views/jobs/jobs.html.erb
<table class="table table-striped  tablesorter">
  <thead>
  <tr>
    <th>Id</th>
    <th>Internal #</th>
    <th>Customer</th>
    <th>Sales Agent</th>
    <th>Job Source</th>
    <th>Job Type</th>
    <th>Created_at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @jobs_job.each do |job| %>
      <tr>
        <td><%= link_to job.id, job_path(job) %></td>
        <td><%= job.internal_job_id %></td>
        <td><%= job.customer.name_with_initial %></td>
        <td><%= if job.sales_agent; job.sales_agent.name_with_initial end %></td>
        <td><%= if job.job_source_id; job.job_source.job_source_name end %></td>
        <td><%= if job.job_type; job.job_type.job_type_name end %></td>
        <td><%=l job.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<p>Showing last 15 - <a href="#all" onclick=" tab6()">View All</a> </p>
<script>
    function tab6(){$("#tab6").load("/jobs/jobs")}
</script>

app/views/jobs/kitchens.html.erb
<table class="table table-striped tablesorter">
  <thead>
  <tr>
    <th>Id</th>
    <th>Internal #</th>
    <th>Customer</th>
    <th>Sales Agent</th>
    <th>Job Source</th>
    <th>Job Status</th>
    <th>Created_at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @jobs_kitchen.each do |job| %>
      <tr>
        <td><%= link_to job.id, job_path(job) %></td>
        <td><%= job.internal_job_id %></td>
        <td><%= job.customer.name_with_initial %></td>
        <td><%= if job.sales_agent; job.sales_agent.name_with_initial end %></td>
        <td><%= if job.job_source_id; job.job_source.job_source_name end %></td>
        <td><%= if job.job_status_id; job.job_status_histories.last.job_status.job_status_name end %></td>
        <td><%=l job.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<p>Showing last 15 - <a href="#all" onclick=" tab3()">View All</a> </p>
<script>
    function tab3(){$("#tab3").load("/jobs/kitchens")}
</script>

app/views/jobs/leads.html.erb
<table class="table table-striped tablesorter">
  <thead>
  <tr>
    <th>Id</th>
    <th>Customer</th>
    <th>Sales Agent</th>
    <th>Job Source</th>
    <th>Job Type</th>
    <th>Created_at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @jobs_lead.each do |job| %>
      <tr>
        <td><%= link_to job.id, job_path(job) %></td>
        <td><%= job.customer.name_with_initial %></td>
        <td><%= if job.sales_agent; job.sales_agent.name_with_initial end %></td>
        <td><%= if job.job_source_id; job.job_source.job_source_name end %></td>
        <td><%= if job.job_type; job.job_type.job_type_name end %></td>
        <td><%=l job.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<p>Showing last 15 - <a href="#all" onclick=" tab4()">View All</a> </p>
<script>
    function tab4(){$("#tab4").load("/jobs/leads")}
</script>

app/views/jobs/new.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/search.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [ 'Find %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<div id="search">
  <%= render :partial => 'jobs/search' %>
</div>

app/views/jobs/show.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal ">
  <div id="customer_jobs" class="span4 pull-right" align="center">
    <div class="panel-group" id="accordion">
      <div class="panel panel-default" id="panel1">
        <div class="panel-heading btn btn-block btn-info dropdown-toggle" data-toggle="collapse" data-target="#collapsecustomer_jobs" href="#">
          <h5 class="panel-title">Status History</h5>
        </div>
        <div id="collapsecustomer_jobs" class="panel-collapse collapse">
          <div class="panel-body well well-small">

            <% if @job.job_status_histories.any? do %>
                <% @job.job_status_histories.each do |status|%>
                    <p><%= status.created_at.to_s + ' - ' + status.job_status.job_status_name %></p>
                <%end%>
            <%end%>
            <%else%>
                Nothing found.
            <% end%>

          </div>
        </div>
      </div>
    </div>

  </div>


  <dt><strong><%= model_class.human_attribute_name(:job_status_id) %>:</strong></dt>
  <dd><%= if @job.job_status_id; @job.job_status_histories.last.job_status.job_status_name end %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer) %>:</strong></dt>
  <dd><%= link_to @job.customer::name_with_initial, customer_path(@job.customer)  %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sales_agent_id) %>:</strong></dt>
  <dd><%= if @job.sales_agent; link_to @job.sales_agent.sales_agent_last_name, sales_agent_path(@job.sales_agent) end%></dd>
  <dt><strong><%= model_class.human_attribute_name(:job_source_id) %>:</strong></dt>
  <dd><%= if @job.job_source; @job.job_source.job_source_name end%></dd>
  <dt><strong><%= model_class.human_attribute_name(:job_type_id) %>:</strong></dt>
  <dd><%= if @job.job_type; @job.job_type.job_type_name end %></dd>
  <dt><strong><%= model_class.human_attribute_name('internal_job_#') %>:</strong></dt>
  <dd><%= @job.internal_job_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:job_price) %>:</strong></dt>
  <dd><%= number_to_currency(@job.job_price) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:job_notes) %>:</strong></dt>
  <dd><%= @job.job_notes.humanize %></dd>
  <hr>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @job.customer_home_address.titleize %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zip) %>:</strong></dt>
  <dd><%=  @job.customer_home_zip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @job.customer_home_city.titleize %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @job.customer_home_state.titleize %></dd>


</dl>




</div>

<br>

<div class="form-actions ">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              jobs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_job_path(@job), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              job_path(@job),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>