config/routes.rb
Cis4375::Application.routes.draw do
  devise_for :users
  get 'pages/home'
  get 'pages/about'
  get 'pages/help'
  get 'pages/faq'
  get 'pages/tutorial'

  get 'customers/new_lead'
  post 'customers/create_lead'

  get 'customers/search'
  get 'jobs/search'
  get 'sales_agents/search'
  get 'job_sources/search'

  get 'jobs/jobs'
  get 'jobs/bids'
  get 'jobs/leads'
  get 'jobs/kitchens'
  get 'jobs/bathrooms'
  get 'jobs/all'

  get 'customers/active'
  get 'customers/inactive'

  resources :sales_agent_statuses

  resources :sales_agents

  resources :job_statuses

  resources :job_status_histories

  resources :job_types

  resources :job_sources

  resources :customer_statuses

  resources :jobs

  resources :customers

   root 'pages#home'

end

app/controllers/job_statuses_controller.rb
class JobStatusesController < ApplicationController
  before_action :set_job_status, only: [:show, :edit, :update, :destroy]

  # GET /job_statuses
  # GET /job_statuses.json
  def index
    @job_statuses = JobStatus.all
  end

  # GET /job_statuses/1
  # GET /job_statuses/1.json
  def show
  end

  # GET /job_statuses/new
  def new
    @job_status = JobStatus.new
  end

  # GET /job_statuses/1/edit
  def edit
  end

  # POST /job_statuses
  # POST /job_statuses.json
  def create
    @job_status = JobStatus.new(job_status_params)

    respond_to do |format|
      if @job_status.save
        format.html { redirect_to @job_status, notice: 'Job status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job_status }
      else
        format.html { render action: 'new' }
        format.json { render json: @job_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_statuses/1
  # PATCH/PUT /job_statuses/1.json
  def update
    respond_to do |format|
      if @job_status.update(job_status_params)
        format.html { redirect_to @job_status, notice: 'Job status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_statuses/1
  # DELETE /job_statuses/1.json
  def destroy
    @job_status.destroy
    respond_to do |format|
      format.html { redirect_to job_statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_status
      @job_status = JobStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_status_params
      params.require(:job_status).permit(:job_status_name)
    end
end

app/helpers/job_statuses_helper.rb
module JobStatusesHelper
end

app/views/job_statuses/_form.html.erb
<%= form_for(@job_status) do |f| %>
  <% if @job_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_status.errors.count, "error") %> prohibited this job_status from being saved:</h2>

      <ul>
      <% @job_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_status_name %><br>
    <%= f.text_field :job_status_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_statuses/edit.html.erb
<h1>Editing job_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_status %> |
<%= link_to 'Back', job_statuses_path %>

app/views/job_statuses/index.html.erb
<h1>Listing job_statuses</h1>

<table>
  <thead>
    <tr>
      <th>Job status name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @job_statuses.each do |job_status| %>
      <tr>
        <td><%= job_status.job_status_name %></td>
        <td><%= link_to 'Show', job_status %></td>
        <td><%= link_to 'Edit', edit_job_status_path(job_status) %></td>
        <td><%= link_to 'Destroy', job_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job status', new_job_status_path %>

app/views/job_statuses/new.html.erb
<h1>New job_status</h1>

<%= render 'form' %>

<%= link_to 'Back', job_statuses_path %>

app/views/job_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job status name:</strong>
  <%= @job_status.job_status_name %>
</p>

<%= link_to 'Edit', edit_job_status_path(@job_status) %> |
<%= link_to 'Back', job_statuses_path %>